FROM alpine:edge

MAINTAINER Huang Rui vowstar@gmail.com

ENV TOOLCHAIN /opt/xtensa-esp108-elf
ENV PATH $(TOOLCHAIN)/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
ENV COMPILE gcc

RUN apk --no-cache add \
        autoconf \
        automake \
        bison \
        bzip2 \
        flex \
        g++ \
        gawk \
        gcc \
        git \
        gperf \
        libtool \
        make \
        ncurses-dev \
        expat-dev \
        nano \
        python \
        py-pip \
        sed \
        texinfo \
        unrar \
        unzip \
        help2man \
        wget \
        expat-dev \
    && pip install pyserial \
    && mkdir -p /opt/crosstool \
    && adduser -D -H -u 1000 build \
    && chown -R build /opt/crosstool \
    && chgrp -R build /opt/crosstool

USER build

RUN cd /opt/crosstool \
    && git clone -b esp108-1.21.0 git://github.com/jcmvbkbc/crosstool-NG.git crosstool-NG \
    && cd crosstool-NG \
    && ./bootstrap \
    && ./configure --prefix=`pwd` \
    && make \
    && make install \
    && ./ct-ng xtensa-esp108-elf \
    && sed -r -i.org s%CT_PREFIX_DIR=.*%CT_PREFIX_DIR="$(TOOLCHAIN)"% .config
    && sed -r -i s%CT_INSTALL_DIR_RO=y%"#"CT_INSTALL_DIR_RO=y% .config
    && ./ct-ng build 

USER root
